config/routes.rb
CleaningDuty::Application.routes.draw do
  get "assignment/index"

  resources :members

  root :to => "assignment#index"

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :week
  belongs_to :member
  belongs_to :duty

end

app/models/assignment_creator.rb
class AssignmentCreator
  def create(start_week)
    duties = Duty.order(:type).all
    members = Member.inside
    # 指定週の残りは後で
    # not_assign_duties = Assignment.not_assign_by_week(start_week)

    weeks_count_to_assign = members.count / duties.count # ここに指定週の残りを引く
    weeks = Week.to_assign(start_week).limit(weeks_count_to_assign)
    
    puts duties.count
    puts weeks_count_to_assign
    p weeks

    weeks.each do |week|
      duties.each do |duty|
        duty.personnel_number.times do
          a = Assignment.new week: week, duty: duty, member: members.pop
          a.save!
        end
      end
    end
  end
end

app/models/duty.rb
class Duty < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  scope :inside, where("outside = ?", false)
end

app/models/week.rb
class Week < ActiveRecord::Base

  has_many :assignments
  has_many :duties, :through => :assignments
  has_many :members, :through => :assignments

  scope :to_assign, lambda {|start| where("start_date > ?", start).order("start_date")}

  def ==(obj)
    self.start_date == obj.start_date
  end

  def full_name
    "#{self.start_date.to_s}  #{self.start_date.cweek} weeks"
  end

  def year
    self.start_date.year
  end

  def cweek
    self.start_date.cweek
  end

  def assign_members(week,duty)
    self.assignments.where("duty_id = ?",duty.id).map{|a| a.member}
  end

  def assign_members_name(week,duty)
    names = ''
    assign_members(week,duty).each do |member|
      names << member.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assignment_controller.rb
class AssignmentController < ApplicationController
  def index
    @duties = Duty.order(:type).all
    @weeks = Week.order(:start_date).all
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to(@member, :notice => 'Member was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to(@member, :notice => 'Member was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to(members_url) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignment_helper.rb
module AssignmentHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/assignment/index.html.erb
<h1>掃除当番管理システムメイン</h1>

<h2>現在の割当</h2>

<table border="1">
  <th></th>
  <th><%= @duties[0].name %></th>
  <th><%= @duties[1].name %></th>
  <th><%= @duties[2].name %></th>
  <% @weeks.each do |week| %>
    <tr>
      <td><%= week.full_name %></td>
      <td><%= week.assign_members_name(week,@duties[0]) %></td>
      <td><%= week.assign_members_name(week,@duties[1]) %></td>
      <td><%= week.assign_members_name(week,@duties[2]) %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CleaningDuty</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :outside %><br />
    <%= f.check_box :outside %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Number</th>
    <th>Email</th>
    <th>Outside</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.name %></td>
    <td><%= member.number %></td>
    <td><%= member.email %></td>
    <td><%= member.outside %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Number:</b>
  <%= @member.number %>
</p>

<p>
  <b>Email:</b>
  <%= @member.email %>
</p>

<p>
  <b>Outside:</b>
  <%= @member.outside %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>